[package]
name = "beaconbridge"
version = "0.1.0"
authors = ["Ville Ilvonen"]
edition = "2018"

[dependencies]
daemonize = { path = "../daemonize" }
btleplug = { path = "../btleplug" }
config = "0.11"
serde = "1.0.125"
serde_derive = "1.0.125"
